import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
const version = pkg.version;

const code = `// Auto-generated by scripts/prebuild.mjs — do not edit manually
export const PLUGIN_VERSION = '${version}';
`;
writeFileSync(join(root, 'src', 'version.ts'), code, 'utf-8');

const manifest = JSON.parse(readFileSync(join(root, 'plugin.json'), 'utf-8'));
if (manifest.version !== version) {
  manifest.version = version;
  writeFileSync(join(root, 'plugin.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf-8');
}

const lock = JSON.parse(readFileSync(join(root, 'package-lock.json'), 'utf-8'));
if (lock.version !== version) {
  lock.version = version;
  writeFileSync(join(root, 'package-lock.json'), JSON.stringify(lock, null, 2) + '\n', 'utf-8');
}

console.log(`[prebuild] synced version ${version} → src/version.ts, plugin.json, package-lock.json`);
